//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PostBookEntities : DbContext
    {
        public PostBookEntities()
            : base("name=PostBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int SP_Create_Random_Comments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_Random_Comments");
        }
    
        public virtual int SP_Create_Random_Posts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_Random_Posts");
        }
    
        public virtual ObjectResult<SP_GET_PostFeedback_Result> SP_GET_PostFeedback(Nullable<int> qryOption)
        {
            var qryOptionParameter = qryOption.HasValue ?
                new ObjectParameter("QryOption", qryOption) :
                new ObjectParameter("QryOption", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PostFeedback_Result>("SP_GET_PostFeedback", qryOptionParameter);
        }
    }
}
